-- Conectado con system/sys/sysdba o admin.

ALTER SESSION SET CONTAINER=freepdb1;
-- CONN sys/oracle AS SYSDBA;


CREATE USER base2 IDENTIFIED BY "Clases.2023"
DEFAULT TABLESPACE users QUOTA UNLIMITED ON users;

GRANT CREATE SESSION, create procedure, CREATE TABLE, CREATE TYPE, CREATE TRIGGER TO base2;
COMMIT;