-- Conectado con system

CONN sys/oracle AS SYSDBA
alter session set "_oracle_script"=TRUE;
ALTER SESSION SET CONTAINER=freepdb1;

CREATE USER base2 IDENTIFIED BY "Clases.2023"
  DEFAULT TABLESPACE users QUOTA UNLIMITED ON users;
  
GRANT CREATE SESSION, CREATE TABLE, CREATE PROCEDURE, CREATE TRIGGER, CREATE TYPE TO base2;
GRANT CONNECT, RESOURCE TO base2;
GRANT CREATE SEQUENCE TO base2;
GRANT CREATE VIEW TO base2;
GRANT CREATE SESSION TO base2;
GRANT CREATE MATERIALIZED VIEW TO base2;
GRANT UNLIMITED TABLESPACE to base2;
COMMIT;